### ISSUE TITLE
Compile fails using Manjaro Linux

### ISSUE THREAD

**Issue by celem** [HarveyBates/kicad-component-handler#1]
Compile fails using Manjaro Linux (Arch based). The issue appears to be because your Windows environment that you are  apparently using  to design kandle is for the newest C++ C17  while my compiler has no <cstdint> or any other C90 includes.  My Linux 5.15.114-2-MANJARO is the latest - it is a rolling release.  I would love to use kandle but it looks like that isn't currently possible.

First lines of make output:
````
[ecomer@asrock build]$ make clean
[ecomer@asrock build]$ make
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ecomer/src/kandle/build
[ 12%] Building CXX object CMakeFiles/kandle.dir/src/eschema/config.cpp.o
[ 25%] Building CXX object CMakeFiles/kandle.dir/src/eschema/legacy.cpp.o
In file included from /home/ecomer/src/kandle/include/eschema/legacy.hpp:34,
                 from /home/ecomer/src/kandle/src/eschema/legacy.cpp:25:
/home/ecomer/src/kandle/include/eschema/component.hpp:35:19: error: ‘UINT8_MAX’ was not declared in this scope
   35 |         char name[UINT8_MAX]{};
      |                   ^~~~~~~~~
/home/ecomer/src/kandle/include/eschema/component.hpp:1:1: note: ‘UINT8_MAX’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
  +++ |+#include <cstdint>
```
`

**Comment by HarveyBates** [comment]
No worries mate, I'll have a look at this tonight

**Comment by HarveyBates** [comment]
Hey mate, 

Can you run:
```bash
gcc --version
```

If its less than v8.xx then I think you will need to update [gcc](https://software.manjaro.org/package/gcc) using:
```bash
pamac install gcc
```

Then you might have to install [base-devel](https://software.manjaro.org/package/base-devel) (development tools) if its still not working.
```bash
pamac install base-devel
```

**Comment by celem** [comment]
$ gcc --version
gcc (GCC) 13.1.1 20230429
$ pamac install base-devel
Preparing...
Warning: base-devel-1-2 is up to date -- skipping
Nothing to do.

**Comment by celem** [comment]
***@***.*** ~]$ gcc --version
gcc (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***@***.*** ~]$ pamac install base-devel
Preparing...
Warning: base-devel-1-2 is up to date -- skipping
Nothing to do.
Transaction successfully finished.

**Comment by HarveyBates** [comment]
ok great, so that looks all good. I've push a commit to hopefully get around your <cstdint> header error. 

You'll need to pull it down, clean your project and rebuild again.

**Comment by celem** [comment]
*Did*:
***@***.*** kandle]$ git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), 559 bytes | 43.00 KiB/s, done.
From https://github.com/HarveyBates/kandle
   49e6cc9..3c7a5cb  main       -> origin/main
Updating 49e6cc9..3c7a5cb
Fast-forward
 CMakeLists.txt                |  9 +++------
 include/eschema/component.hpp | 12 ++++++------
 2 files changed, 9 insertions(+), 12 deletions(-)

*Next*:
***@***.*** build]$ make clean
***@***.*** build]$ cmake ..
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ecomer/src/kandle/build
***@***.*** build]$ make
[ 12%] Building CXX object CMakeFiles/kandle.dir/src/eschema/config.cpp.o
[ 25%] Building CXX object CMakeFiles/kandle.dir/src/eschema/legacy.cpp.o
/home/ecomer/src/kandle/src/eschema/legacy.cpp: In member function ‘bool
Legacy::convert(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/ecomer/src/kandle/src/eschema/legacy.cpp:36:14: error:
‘istream_iterator’ is not a member of ‘std’
   36 |         std::istream_iterator<std::string> it(strstr);
      |              ^~~~~~~~~~~~~~~~
/home/ecomer/src/kandle/src/eschema/legacy.cpp:26:1: note:
‘std::istream_iterator’ is defined in header ‘<iterator>’; did you forget
to ‘#include <iterator>’?
   25 | #include "eschema/legacy.hpp"
  +++ |+#include <iterator>
   26 |
/home/ecomer/src/kandle/src/eschema/legacy.cpp:36:42: error: expected
primary-expression before ‘>’ token
   36 |         std::istream_iterator<std::string> it(strstr);
      |                                          ^
/home/ecomer/src/kandle/src/eschema/legacy.cpp:36:44: error: ‘it’ was not
declared in this scope; did you mean ‘int’?
   36 |         std::istream_iterator<std::string> it(strstr);
      |                                            ^~
      |                                            int
/home/ecomer/src/kandle/src/eschema/legacy.cpp:37:14: error:
‘istream_iterator’ is not a member of ‘std’
   37 |         std::istream_iterator<std::string> end;
      |              ^~~~~~~~~~~~~~~~
/home/ecomer/src/kandle/src/eschema/legacy.cpp:37:14: note:
‘std::istream_iterator’ is defined in header ‘<iterator>’; did you forget
to ‘#include <iterator>’?
/home/ecomer/src/kandle/src/eschema/legacy.cpp:37:42: error: expected
primary-expression before ‘>’ token
   37 |         std::istream_iterator<std::string> end;
      |                                          ^
/home/ecomer/src/kandle/src/eschema/legacy.cpp:37:44: error: ‘end’ was not
declared in this scope; did you mean ‘std::end’?
   37 |         std::istream_iterator<std::string> end;
      |                                            ^~~
      |                                            std::end
In file included from /usr/include/c++/13.1.1/string:53,
                 from /usr/include/c++/13.1.1/bits/locale_classes.h:40,
                 from /usr/include/c++/13.1.1/bits/ios_base.h:41,
                 from /usr/include/c++/13.1.1/ios:44,
                 from /usr/include/c++/13.1.1/ostream:40,
                 from /usr/include/c++/13.1.1/iostream:41,
                 from /home/ecomer/src/kandle/include/eschema/legacy.hpp:27,
                 from /home/ecomer/src/kandle/src/eschema/legacy.cpp:25:
/usr/include/c++/13.1.1/bits/range_access.h:116:37: note: ‘std::end’
declared here
  116 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&)
noexcept;
      |                                     ^~~
/home/ecomer/src/kandle/src/eschema/legacy.cpp: In member function ‘bool
Legacy::parse_pin(const std::string&)’:
/home/ecomer/src/kandle/src/eschema/legacy.cpp:161:13: error: ‘strlen’ was
not declared in this scope
  161 |         if (strlen(pin.name) != 0) {
      |             ^~~~~~
/home/ecomer/src/kandle/src/eschema/legacy.cpp:26:1: note: ‘strlen’ is
defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   25 | #include "eschema/legacy.hpp"
  +++ |+#include <cstring>
   26 |
In file included from /home/ecomer/src/kandle/include/eschema/legacy.hpp:36:
/home/ecomer/src/kandle/include/utils.hpp: At global scope:
/home/ecomer/src/kandle/include/utils.hpp:33:20: error: ‘KICAD_GENERATOR’
defined but not used [-Werror=unused-variable]
   33 | static const char* KICAD_GENERATOR = "kicad_symbol_editor";
      |                    ^~~~~~~~~~~~~~~
/home/ecomer/src/kandle/include/utils.hpp:32:20: error: ‘KICAD_VERSION’
defined but not used [-Werror=unused-variable]
   32 | static const char* KICAD_VERSION = "20211014";
      |                    ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/kandle.dir/build.make:90:
CMakeFiles/kandle.dir/src/eschema/legacy.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/kandle.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by HarveyBates** [comment]
Hey mate, if you have time, have another go. I've updated the repository and checked it using a docker image of manjaro and it compiles.

**Comment by celem** [comment]
Thank you. I compiled correctly and executes. I will test it with a copy of a small project, today if possible, and will provide feedback when done. It looks very promising and useful.
