### ISSUE TITLE
Core dump with V4 resistor

### ISSUE THREAD

**Issue by celem** [HarveyBates/kicad-component-handler#2]
I tested kandle with an existing small project with three parts. A transistor worked fine but it core dumped with an 0805 SMD resistor at:
[Mouser part LINK](https://www.mouser.com/ProductDetail/YAGEO/RC0805FR-074K7L?qs=VLOqbHBAO5cYXbrd7RTmuQ%3D%3D
)
The console output was:
`ecomer@asrock level-shifter]$ kandle -f /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip -l Resistor_0805
Extracting from: /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip
Extracting to: components/extern/tmp/RC0805DR-074K7L
Output directory: components/extern/tmp/RC0805DR-074K7L already exists.
Converting legacy file.
/usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1239: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
`
BTW Output shows "components/extern/tmp/RC0805DR-074K7L already exists" because it was created by a previous attempt using the same part from digikey.com, which core dumped in the same way.

**Comment by HarveyBates** [comment]
Kandle is detecting the directory you downloaded from Digikey already exists in the folder `components/extern/tmp` so it doesn't overwrite it. 

You will have to delete the folder: `components/extern/tmp/RC0805DR-074K7L` and then rerun: 
``` bash
kandle -f /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip -l Resistor_0805
```

**Comment by celem** [comment]
**Thank you but that doesn't seem to be the problem. Here is the command line:**
`[ecomer@asrock level-shifter]$ ls /home/ecomer/Drive/level-shifter/components/extern/tmp
MBT3904DW1T1G  RC0805DR-074K7L
[ecomer@asrock level-shifter]$ rm -r /home/ecomer/Drive/level-shifter/components/extern/tmp/RC0805DR-074K7L
[ecomer@asrock level-shifter]$ ls /home/ecomer/Drive/level-shifter/components/extern/tmp
MBT3904DW1T1G
[ecomer@asrock level-shifter]$ kandle -f /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip -l Resistor_0805
Extracting from: /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip
Extracting to: components/extern/tmp/RC0805DR-074K7L
Successfully extracted to: components/extern/tmp/RC0805DR-074K7L
Found 3D model: "components/extern/tmp/RC0805DR-074K7L/RC0805FR-074K7L/3D/RC0805FR-074K7L.stp"
Component Search Engine component detected.
Converting legacy file.
/usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1239: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
`
**It seems to be a problem with the data format from DigiKey versus SnapEda. I downloaded the same data in from SnapEda and here is the successful command line. BTW I did it twice so that the tmp folder would already be there.**
`ecomer@asrock level-shifter]$ kandle -f /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip -l Resistor_0805
Extracting from: /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip
Extracting to: components/extern/tmp/RC0805DR-074K7L
Successfully extracted to: components/extern/tmp/RC0805DR-074K7L
Found symbol: "components/extern/tmp/RC0805DR-074K7L/RC0805DR-074K7L.kicad_sym"
Found 3D model: "components/extern/tmp/RC0805DR-074K7L/RC0805DR-074K7L.step"
Found footprint: "components/extern/tmp/RC0805DR-074K7L/RESC2012X60N.kicad_mod"
Creating new symbol library: components/extern/symbols/Resistor_0805.kicad_sym
[ecomer@asrock level-shifter]$ kandle -f /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip -l Resistor_0805
Extracting from: /home/ecomer/Downloads/hold/RC0805DR-074K7L.zip
Extracting to: components/extern/tmp/RC0805DR-074K7L
Output directory: components/extern/tmp/RC0805DR-074K7L already exists.
Found symbol: "components/extern/tmp/RC0805DR-074K7L/RC0805DR-074K7L.kicad_sym"
Found 3D model: "components/extern/tmp/RC0805DR-074K7L/RC0805DR-074K7L.step"
Found footprint: "components/extern/tmp/RC0805DR-074K7L/RESC2012X60N.kicad_mod"
Component already exists in symbol library.
`

**Comment by HarveyBates** [comment]
Yea I think the reason why it doesn't work is digikeys format. Currently Kandle only supports snapeda, ultra librarian and component search engine. The reason mouser works is because they use component search engine under the hood.
